use crate::types::edn::Edn;
use pgrx::prelude::*;

// Note: = and <> operators are auto-generated by #[derive(PostgresEq)] on Edn.
// Do NOT define them here or CREATE EXTENSION will fail with "operator = already exists".

/// Get value from map by key
/// Example: edn_get('{:name "Alice"}', ':name') -> '"Alice"'
#[pg_extern(immutable, parallel_safe)]
fn edn_get(map: Edn, key: Edn) -> Option<Edn> {
    match map.inner() {
        edn::Value::Map(m) => m.get(key.inner()).map(|v| Edn::new(v.clone())),
        _ => None,
    }
}

/// Get value from vector by index (0-based)
/// Example: edn_nth('[1 2 3]', 1) -> 2
#[pg_extern(immutable, parallel_safe)]
fn edn_nth(vec: Edn, index: i64) -> Option<Edn> {
    match vec.inner() {
        edn::Value::Vector(v) => {
            if index < 0 || index >= v.len() as i64 {
                None
            } else {
                Some(Edn::new(v[index as usize].clone()))
            }
        }
        _ => None,
    }
}

/// Get count of elements in a collection
/// Example: edn_count('[1 2 3]') -> 3
#[pg_extern(immutable, parallel_safe)]
fn edn_count(value: Edn) -> i64 {
    match value.inner() {
        edn::Value::Vector(v) => v.len() as i64,
        edn::Value::List(l) => l.len() as i64,
        edn::Value::Set(s) => s.len() as i64,
        edn::Value::Map(m) => m.len() as i64,
        _ => 0,
    }
}

/// Check if a value is nil
#[pg_extern(immutable, parallel_safe)]
fn edn_is_nil(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Nil)
}

/// Check if a value is a boolean
#[pg_extern(immutable, parallel_safe)]
fn edn_is_boolean(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Boolean(_))
}

/// Check if a value is an integer
#[pg_extern(immutable, parallel_safe)]
fn edn_is_integer(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Integer(_))
}

/// Check if a value is a float
#[pg_extern(immutable, parallel_safe)]
fn edn_is_float(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Float(_))
}

/// Check if a value is a string
#[pg_extern(immutable, parallel_safe)]
fn edn_is_text(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Text(_))
}

/// Check if a value is a keyword
#[pg_extern(immutable, parallel_safe)]
fn edn_is_keyword(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Keyword(_))
}

/// Check if a value is a vector
#[pg_extern(immutable, parallel_safe)]
fn edn_is_vector(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Vector(_))
}

/// Check if a value is a list
#[pg_extern(immutable, parallel_safe)]
fn edn_is_list(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::List(_))
}

/// Check if a value is a set
#[pg_extern(immutable, parallel_safe)]
fn edn_is_set(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Set(_))
}

/// Check if a value is a map
#[pg_extern(immutable, parallel_safe)]
fn edn_is_map(value: Edn) -> bool {
    matches!(value.inner(), edn::Value::Map(_))
}

/// Check if a collection contains an element
#[pg_extern(immutable, parallel_safe)]
fn edn_contains(collection: Edn, element: Edn) -> bool {
    match collection.inner() {
        edn::Value::Vector(v) => v.contains(element.inner()),
        edn::Value::List(l) => l.iter().any(|item| item == element.inner()),
        edn::Value::Set(s) => s.contains(element.inner()),
        edn::Value::Map(m) => m.contains_key(element.inner()),
        _ => false,
    }
}

/// Extract keys from a map as a vector
#[pg_extern(immutable, parallel_safe)]
fn edn_keys(map: Edn) -> Option<Edn> {
    match map.inner() {
        edn::Value::Map(m) => {
            let keys: Vec<edn::Value> = m.keys().cloned().collect();
            Some(Edn::new(edn::Value::Vector(keys)))
        }
        _ => None,
    }
}

/// Extract values from a map as a vector
#[pg_extern(immutable, parallel_safe)]
fn edn_values(map: Edn) -> Option<Edn> {
    match map.inner() {
        edn::Value::Map(m) => {
            let values: Vec<edn::Value> = m.values().cloned().collect();
            Some(Edn::new(edn::Value::Vector(values)))
        }
        _ => None,
    }
}
