apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mentatd
  namespace: pg-mentat
  labels:
    app.kubernetes.io/name: mentatd
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mentatd
      app.kubernetes.io/component: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pg-mentat-postgres
  namespace: pg-mentat
  labels:
    app.kubernetes.io/name: pg-mentat-postgres
    app.kubernetes.io/component: database
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pg-mentat-postgres
      app.kubernetes.io/component: database
