{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pg-mentat.fullname" . }}
  labels:
    {{- include "pg-mentat.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  podSelector:
    matchLabels:
      {{- include "pg-mentat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: {{ .Values.mentatd.config.port }}
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "pg-mentat.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: database
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pg-mentat.postgresql.fullname" . }}
  labels:
    {{- include "pg-mentat.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  podSelector:
    matchLabels:
      {{- include "pg-mentat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "pg-mentat.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: server
      ports:
        - port: 5432
          protocol: TCP
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
