{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pg-mentat.fullname" . }}
  labels:
    {{- include "pg-mentat.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "pg-mentat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
