{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-mentat.postgresql.secretName" . }}
  labels:
    {{- include "pg-mentat.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-user: {{ .Values.postgresql.auth.username | b64enc }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
  postgres-db: {{ .Values.postgresql.auth.database | b64enc }}
{{- end }}
