{{- if .Values.mentatd.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pg-mentat.serviceAccountName" . }}
  labels:
    {{- include "pg-mentat.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}
