/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/lib.rs:6


    -- Define enum types
    DO $$ BEGIN
        CREATE TYPE mentat.value_type AS ENUM (
            'ref', 'boolean', 'instant', 'long', 'double', 'string', 'keyword', 'uuid', 'bytes'
        );
    EXCEPTION WHEN duplicate_object THEN null;
    END $$;

    DO $$ BEGIN
        CREATE TYPE mentat.unique_type AS ENUM ('value', 'identity');
    EXCEPTION WHEN duplicate_object THEN null;
    END $$;

    DO $$ BEGIN
        CREATE TYPE mentat.cardinality_type AS ENUM ('one', 'many');
    EXCEPTION WHEN duplicate_object THEN null;
    END $$;

    -- Datoms table partitioned by value_type_tag for partition pruning
    CREATE TABLE IF NOT EXISTS mentat.datoms (
        e BIGINT NOT NULL,
        a BIGINT NOT NULL,
        value_type_tag SMALLINT NOT NULL,
        v_ref BIGINT,
        v_bool BOOLEAN,
        v_long BIGINT,
        v_double DOUBLE PRECISION,
        v_text TEXT,
        v_keyword TEXT,
        v_instant TIMESTAMPTZ,
        v_uuid UUID,
        v_bytes BYTEA,
        tx BIGINT NOT NULL,
        added BOOLEAN NOT NULL DEFAULT TRUE,

        -- Ensure exactly one value column is populated per row
        CONSTRAINT chk_datom_value CHECK (
            (CASE WHEN v_ref IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_bool IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_long IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_double IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_text IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_keyword IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_instant IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_uuid IS NOT NULL THEN 1 ELSE 0 END
           + CASE WHEN v_bytes IS NOT NULL THEN 1 ELSE 0 END) = 1
        )
    ) PARTITION BY LIST (value_type_tag);

    -- Create partitions for each value type
    CREATE TABLE IF NOT EXISTS mentat.datoms_ref PARTITION OF mentat.datoms FOR VALUES IN (0);
    CREATE TABLE IF NOT EXISTS mentat.datoms_bool PARTITION OF mentat.datoms FOR VALUES IN (1);
    CREATE TABLE IF NOT EXISTS mentat.datoms_long PARTITION OF mentat.datoms FOR VALUES IN (2);
    CREATE TABLE IF NOT EXISTS mentat.datoms_double PARTITION OF mentat.datoms FOR VALUES IN (3);
    CREATE TABLE IF NOT EXISTS mentat.datoms_instant PARTITION OF mentat.datoms FOR VALUES IN (4);
    CREATE TABLE IF NOT EXISTS mentat.datoms_text PARTITION OF mentat.datoms FOR VALUES IN (7);
    CREATE TABLE IF NOT EXISTS mentat.datoms_keyword PARTITION OF mentat.datoms FOR VALUES IN (8);
    CREATE TABLE IF NOT EXISTS mentat.datoms_uuid PARTITION OF mentat.datoms FOR VALUES IN (10);
    CREATE TABLE IF NOT EXISTS mentat.datoms_bytes PARTITION OF mentat.datoms FOR VALUES IN (11);
    CREATE TABLE IF NOT EXISTS mentat.datoms_default PARTITION OF mentat.datoms DEFAULT;

    CREATE TABLE IF NOT EXISTS mentat.schema (
        entid BIGINT PRIMARY KEY,
        ident TEXT UNIQUE NOT NULL,
        value_type mentat.value_type NOT NULL,
        cardinality mentat.cardinality_type NOT NULL DEFAULT 'one',
        unique_constraint mentat.unique_type,
        indexed BOOLEAN NOT NULL DEFAULT FALSE,
        fulltext BOOLEAN NOT NULL DEFAULT FALSE,
        component BOOLEAN NOT NULL DEFAULT FALSE,
        no_history BOOLEAN NOT NULL DEFAULT FALSE
    );

    CREATE TABLE IF NOT EXISTS mentat.idents (
        ident TEXT PRIMARY KEY,
        entid BIGINT UNIQUE NOT NULL
    );

    CREATE TABLE IF NOT EXISTS mentat.partitions (
        name TEXT PRIMARY KEY,
        start_entid BIGINT NOT NULL,
        end_entid BIGINT NOT NULL,
        next_entid BIGINT NOT NULL,
        allow_excision BOOLEAN NOT NULL DEFAULT FALSE
    );

    CREATE TABLE IF NOT EXISTS mentat.transactions (
        tx BIGINT PRIMARY KEY,
        tx_instant TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    -- Core datom indexes (reduced from 22 to 8 for write throughput)
    -- EAVT: Entity-centric lookups (partial on added=TRUE)
    CREATE INDEX IF NOT EXISTS idx_datoms_eavt ON mentat.datoms (e, a, value_type_tag, tx) WHERE added = TRUE;
    -- AEVT: Attribute-centric scans (partial on added=TRUE)
    CREATE INDEX IF NOT EXISTS idx_datoms_aevt ON mentat.datoms (a, e, value_type_tag, tx) WHERE added = TRUE;
    -- TX: Transaction history lookups
    CREATE INDEX IF NOT EXISTS idx_datoms_tx ON mentat.datoms (tx DESC);
    -- VAET: Reverse ref lookups (refs only)
    CREATE INDEX IF NOT EXISTS idx_datoms_vaet ON mentat.datoms (v_ref, a, e, tx) WHERE added = TRUE AND value_type_tag = 0;

    -- Type-specific AVET indexes (only high-frequency types)
    CREATE INDEX IF NOT EXISTS idx_datoms_avet_ref ON mentat.datoms (a, v_ref, e, tx) WHERE added = TRUE AND value_type_tag = 0;
    CREATE INDEX IF NOT EXISTS idx_datoms_avet_long ON mentat.datoms (a, v_long, e, tx) WHERE added = TRUE AND value_type_tag = 2;
    CREATE INDEX IF NOT EXISTS idx_datoms_avet_text ON mentat.datoms (a, v_text, e, tx) WHERE added = TRUE AND value_type_tag = 7;
    CREATE INDEX IF NOT EXISTS idx_datoms_avet_keyword ON mentat.datoms (a, v_keyword, e, tx) WHERE added = TRUE AND value_type_tag = 8;

    -- Configure autovacuum for high-churn temporal workloads
    -- Vacuum at 5% dead tuples (vs default 20%) to prevent index bloat from retractions
    ALTER TABLE mentat.datoms SET (
        autovacuum_vacuum_scale_factor = 0.05,
        autovacuum_analyze_scale_factor = 0.02
    );

    -- Full-text search support table
    CREATE TABLE IF NOT EXISTS mentat.fulltext (
        text_value TEXT NOT NULL,
        search_vector TSVECTOR
    );
    CREATE INDEX IF NOT EXISTS idx_fulltext_search ON mentat.fulltext USING GIN (search_vector);

    -- Trigger to auto-update search vector
    CREATE OR REPLACE FUNCTION mentat.fulltext_update_trigger() RETURNS trigger AS $$
    BEGIN
        NEW.search_vector := to_tsvector('english', NEW.text_value);
        RETURN NEW;
    END; $$ LANGUAGE plpgsql;

    DROP TRIGGER IF EXISTS fulltext_update ON mentat.fulltext;
    CREATE TRIGGER fulltext_update BEFORE INSERT OR UPDATE ON mentat.fulltext
        FOR EACH ROW EXECUTE FUNCTION mentat.fulltext_update_trigger();

    INSERT INTO mentat.partitions (name, start_entid, end_entid, next_entid, allow_excision) VALUES
        ('db.part/db', 0, 10000, 100, FALSE),
        ('db.part/user', 10000, 1000000, 10000, FALSE),
        ('db.part/tx', 1000000, 2000000, 1000001, FALSE)
    ON CONFLICT (name) DO NOTHING;

    -- Sequences for lock-free entity ID allocation (replaces UPDATE-based locking)
    -- CACHE 100 pre-allocates IDs per connection for high concurrency
    CREATE SEQUENCE IF NOT EXISTS mentat.partition_db_seq START WITH 100 CACHE 10;
    CREATE SEQUENCE IF NOT EXISTS mentat.partition_user_seq START WITH 10000 CACHE 100;
    CREATE SEQUENCE IF NOT EXISTS mentat.partition_tx_seq START WITH 1000001 CACHE 100;

    INSERT INTO mentat.transactions (tx, tx_instant)
    VALUES (1000000, '2025-01-01T00:00:00Z')
    ON CONFLICT (tx) DO NOTHING;

    -- PL/pgSQL helper functions for transaction processing
    -- allocate_entid uses sequences for lock-free concurrent ID allocation
    CREATE OR REPLACE FUNCTION mentat.allocate_entid(partition_name TEXT)
    RETURNS BIGINT AS $$
    BEGIN
        CASE partition_name
            WHEN 'db.part/db' THEN RETURN nextval('mentat.partition_db_seq');
            WHEN 'db.part/user' THEN RETURN nextval('mentat.partition_user_seq');
            WHEN 'db.part/tx' THEN RETURN nextval('mentat.partition_tx_seq');
            ELSE RAISE EXCEPTION 'Partition % not found', partition_name;
        END CASE;
    END; $$ LANGUAGE plpgsql;

    CREATE OR REPLACE FUNCTION mentat.resolve_ident(keyword TEXT)
    RETURNS BIGINT AS $$
    BEGIN
        RETURN (SELECT entid FROM mentat.idents WHERE ident = keyword);
    END; $$ LANGUAGE plpgsql;
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/planner/hooks.rs:97
-- pg_mentat::planner::hooks::analyze_query
CREATE  FUNCTION "analyze_query"(
	"query_text" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'analyze_query_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/planner/hooks.rs:64
-- pg_mentat::planner::hooks::estimate_query_cost
CREATE  FUNCTION "estimate_query_cost"(
	"access_pattern" TEXT, /* &str */
	"estimated_rows" bigint /* i64 */
) RETURNS double precision /* core::result::Result<f64, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'estimate_query_cost_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/planner/hooks.rs:134
-- pg_mentat::planner::hooks::get_index_info
CREATE  FUNCTION "get_index_info"() RETURNS TABLE (
	"index_name" TEXT,  /* alloc::string::String */
	"access_pattern" TEXT,  /* alloc::string::String */
	"use_when" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_index_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/entity.rs:30
-- pg_mentat::functions::entity::mentat_entity
CREATE  FUNCTION "mentat_entity"(
	"entity_id" bigint /* i64 */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/query.rs:627
-- pg_mentat::functions::query::mentat_explain
CREATE  FUNCTION "mentat_explain"(
	"query" TEXT, /* &str */
	"inputs" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_explain_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/pull.rs:151
-- pg_mentat::functions::pull::mentat_pull
CREATE  FUNCTION "mentat_pull"(
	"pattern" TEXT, /* &str */
	"entity_id" bigint /* i64 */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_pull_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/pull.rs:197
-- pg_mentat::functions::pull::mentat_pull_many
CREATE  FUNCTION "mentat_pull_many"(
	"pattern" TEXT, /* &str */
	"entity_ids" bigint[] /* alloc::vec::Vec<i64> */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_pull_many_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/query.rs:511
-- pg_mentat::functions::query::mentat_query
CREATE  FUNCTION "mentat_query"(
	"query" TEXT, /* &str */
	"inputs" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_query_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/stats.rs:39
-- pg_mentat::functions::stats::mentat_query_stats
CREATE  FUNCTION "mentat_query_stats"() RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_query_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/schema.rs:24
-- pg_mentat::functions::schema::mentat_schema
CREATE  FUNCTION "mentat_schema"() RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/stats.rs:212
-- pg_mentat::functions::stats::mentat_slow_queries
CREATE  FUNCTION "mentat_slow_queries"(
	"threshold_ms" double precision DEFAULT 100.0 /* f64 */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_slow_queries_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/query.rs:728
-- pg_mentat::functions::query::mentat_stmt_cache_clear
CREATE  FUNCTION "mentat_stmt_cache_clear"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_stmt_cache_clear_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/query.rs:691
-- pg_mentat::functions::query::mentat_stmt_cache_stats
CREATE  FUNCTION "mentat_stmt_cache_stats"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_stmt_cache_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/stats.rs:352
-- pg_mentat::functions::stats::mentat_storage_stats
CREATE  FUNCTION "mentat_storage_stats"() RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_storage_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/transact.rs:171
-- pg_mentat::functions::transact::mentat_transact
CREATE  FUNCTION "mentat_transact"(
	"edn_tx" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mentat_transact_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/planner/hooks.rs:42
-- pg_mentat::planner::hooks::suggest_index
CREATE  FUNCTION "suggest_index"(
	"access_pattern" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'suggest_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/lib.rs:302
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::EdnValue
CREATE TYPE mentat.EdnValue;

-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::ednvalue_in
CREATE  FUNCTION mentat."ednvalue_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS mentat.EdnValue /* core::option::Option<pg_mentat::mentat::EdnValue> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ednvalue_in_wrapper';

-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::ednvalue_out
CREATE  FUNCTION mentat."ednvalue_out"(
	"input" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ednvalue_out_wrapper';

-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::EdnValue
CREATE TYPE mentat.EdnValue (
	INTERNALLENGTH = variable,
	INPUT = mentat.ednvalue_in, /* pg_mentat::mentat::ednvalue_in */
	OUTPUT = mentat.ednvalue_out, /* pg_mentat::mentat::ednvalue_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/types/edn.rs:137
-- pg_mentat::types::edn::edn_in
CREATE  FUNCTION "edn_in"(
	"input" TEXT /* &str */
) RETURNS mentat.EdnValue /* core::result::Result<pg_mentat::mentat::EdnValue, alloc::boxed::Box<dyn core::error::Error>> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_in_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:71
-- pg_mentat::operators::edn_is_text
CREATE  FUNCTION "edn_is_text"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:47
-- pg_mentat::operators::edn_is_nil
CREATE  FUNCTION "edn_is_nil"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_nil_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:65
-- pg_mentat::operators::edn_is_float
CREATE  FUNCTION "edn_is_float"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_float_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:35
-- pg_mentat::operators::edn_count
CREATE  FUNCTION "edn_count"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/types/edn.rs:160
-- pg_mentat::types::edn::edn_out
CREATE  FUNCTION "edn_out"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_out_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:77
-- pg_mentat::operators::edn_is_keyword
CREATE  FUNCTION "edn_is_keyword"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_keyword_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/types/edn.rs:167
-- pg_mentat::types::edn::edn_send
CREATE  FUNCTION "edn_send"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_send_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:59
-- pg_mentat::operators::edn_is_integer
CREATE  FUNCTION "edn_is_integer"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_integer_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:131
-- pg_mentat::operators::edn_values
CREATE  FUNCTION "edn_values"(
	"map" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS mentat.EdnValue /* core::option::Option<pg_mentat::mentat::EdnValue> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_values_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:19
-- pg_mentat::operators::edn_nth
CREATE  FUNCTION "edn_nth"(
	"vec" mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	"index" bigint /* i64 */
) RETURNS mentat.EdnValue /* core::option::Option<pg_mentat::mentat::EdnValue> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_nth_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/types/edn.rs:175
-- pg_mentat::types::edn::edn_recv
CREATE  FUNCTION "edn_recv"(
	"data" bytea /* alloc::vec::Vec<u8> */
) RETURNS mentat.EdnValue /* core::result::Result<pg_mentat::mentat::EdnValue, alloc::boxed::Box<dyn core::error::Error>> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_recv_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:119
-- pg_mentat::operators::edn_keys
CREATE  FUNCTION "edn_keys"(
	"map" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS mentat.EdnValue /* core::option::Option<pg_mentat::mentat::EdnValue> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_keys_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:95
-- pg_mentat::operators::edn_is_set
CREATE  FUNCTION "edn_is_set"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:101
-- pg_mentat::operators::edn_is_map
CREATE  FUNCTION "edn_is_map"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_map_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:89
-- pg_mentat::operators::edn_is_list
CREATE  FUNCTION "edn_is_list"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_list_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:83
-- pg_mentat::operators::edn_is_vector
CREATE  FUNCTION "edn_is_vector"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_vector_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:9
-- pg_mentat::operators::edn_get
CREATE  FUNCTION "edn_get"(
	"map" mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	"key" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS mentat.EdnValue /* core::option::Option<pg_mentat::mentat::EdnValue> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_get_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:107
-- pg_mentat::operators::edn_contains
CREATE  FUNCTION "edn_contains"(
	"collection" mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	"element" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/operators.rs:53
-- pg_mentat::operators::edn_is_boolean
CREATE  FUNCTION "edn_is_boolean"(
	"value" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'edn_is_boolean_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/helpers.rs:152
-- pg_mentat::functions::helpers::retract_entity
CREATE  FUNCTION mentat."retract_entity"(
	"entity_id" bigint /* i64 */
) RETURNS bigint /* core::result::Result<i64, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'retract_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::ednvalue_eq
CREATE  FUNCTION mentat."ednvalue_eq"(
	"left" mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	"right" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ednvalue_eq_wrapper';

-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::ednvalue_eq
CREATE OPERATOR mentat.= (
	PROCEDURE=mentat."ednvalue_eq",
	LEFTARG=mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	RIGHTARG=mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	COMMUTATOR = =,
	NEGATOR = <>,
	RESTRICT = eqsel,
	JOIN = eqjoinsel,
	HASHES,
	MERGES
);
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/edn_helpers.rs:353
-- pg_mentat::functions::edn_helpers::import_edn
CREATE  FUNCTION mentat."import_edn"(
	"edn_data" TEXT /* &str */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_edn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/edn_helpers.rs:267
-- pg_mentat::functions::edn_helpers::export_edn
CREATE  FUNCTION mentat."export_edn"(
	"entity_ids" bigint[] /* alloc::vec::Vec<i64> */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'export_edn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/helpers.rs:60
-- pg_mentat::functions::helpers::entity_attrs
CREATE  FUNCTION mentat."entity_attrs"(
	"entity_id" bigint /* i64 */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'entity_attrs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/lib.rs:335
-- pg_mentat::mentat::initialize_schema
CREATE  FUNCTION mentat."initialize_schema"() RETURNS VOID /* core::result::Result<(), alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'initialize_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/edn_helpers.rs:35
-- pg_mentat::functions::edn_helpers::batch
CREATE  FUNCTION mentat."batch"(
	"edn_batch" TEXT /* &str */
) RETURNS jsonb /* core::result::Result<pgrx::datum::json::JsonB, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::ednvalue_ne
CREATE  FUNCTION mentat."ednvalue_ne"(
	"left" mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	"right" mentat.EdnValue /* pg_mentat::mentat::EdnValue */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ednvalue_ne_wrapper';

-- pg_mentat/src/lib.rs:310
-- pg_mentat::mentat::ednvalue_ne
CREATE OPERATOR mentat.<> (
	PROCEDURE=mentat."ednvalue_ne",
	LEFTARG=mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	RIGHTARG=mentat.EdnValue, /* pg_mentat::mentat::EdnValue */
	COMMUTATOR = <>,
	NEGATOR = =,
	RESTRICT = neqsel,
	JOIN = neqjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/edn_helpers.rs:372
-- pg_mentat::functions::edn_helpers::query_export_edn
CREATE  FUNCTION mentat."query_export_edn"(
	"query" TEXT, /* &str */
	"inputs" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'query_export_edn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/helpers.rs:100
-- pg_mentat::functions::helpers::attribute_values
CREATE  FUNCTION mentat."attribute_values"(
	"attr_ident" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'attribute_values_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/helpers.rs:34
-- pg_mentat::functions::helpers::lookup_by_ident
CREATE  FUNCTION mentat."lookup_by_ident"(
	"attr_ident" TEXT, /* &str */
	"value" TEXT /* &str */
) RETURNS bigint /* core::option::Option<i64> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'lookup_by_ident_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pg_mentat/src/functions/edn_helpers.rs:410
-- pg_mentat::functions::edn_helpers::export_all_edn
CREATE  FUNCTION mentat."export_all_edn"() RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>> */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'export_all_edn_wrapper';
/* </end connected objects> */

